config/routes.rb
Rails.application.routes.draw do
  resources :moos

  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about' 

end

app/models/moo.rb
class Moo < ActiveRecord::Base
  validates :content, presence: true
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :moos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/moos_controller.rb
class MoosController < ApplicationController
  before_action :set_moo, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  respond_to :html

  def index
    @moos = Moo.all
    respond_with(@moos)
  end

  def show
    respond_with(@moo)
  end

  def new
    @moo = Moo.new
    respond_with(@moo)
  end

  def edit
  end

  def create
    @moo = Moo.new(moo_params)
    @moo.user_id = current_user.id
    @moo.save
    respond_with(@moo)
  end

  def update
    @moo.update(moo_params)
    respond_with(@moo)
  end

  def destroy
    @moo.destroy
    respond_with(@moo)
  end

  private
    def set_moo
      @moo = Moo.find(params[:id])
    end

    def moo_params
      params.require(:moo).permit(:content)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/moos_helper.rb
module MoosHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user %>
            <%= link_to "<i class='fa fa-bullhorn'></i> Bullhorn".html_safe, moos_path, class: "navbar-brand" %> 
    <% else %>
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
     <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      
    
          
      
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
    
        <li><%= link_to "Settings", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
             <% else %>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bullhorn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
<div class="container">

<%= yield %>
  </div>
</body>
</html>

app/views/moos/_form.html.erb
<%= simple_form_for(@moo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/moos/edit.html.erb
<h1>Editing moo</h1>

<%= render 'form' %>

<%= link_to 'Show', @moo %> |
<%= link_to 'Back', moos_path %>

app/views/moos/index.html.erb
<h1>Recent Moos</h1>


    <% @moos.each do |moo| %>
    

<div class="panel panel-default">
  <div class="panel-body">
    <%= moo.content %>
  </div>
  <div class="panel-footer">    sent by <%= moo.user.email %> on <%= 
  moo.created_at.strftime("%m/%d/%Y") %> at <%= 
  moo.created_at.strftime("%I:%M%p")%></div>
</div>
    <% end %>
 

<br>

<%= link_to 'New Moo', new_moo_path %>

app/views/moos/new.html.erb
<h1>New moo</h1>

<%= render 'form' %>

<%= link_to 'Back', moos_path %>

app/views/moos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @moo.content %>
</p>

<%= link_to 'Edit', edit_moo_path(@moo) %> |
<%= link_to 'Back', moos_path %>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1><i class="fa fa-bullhorn"></i>Bullhorn!</h1>
  <p>This is my Twitter clone Application</p>
  <% if current_user %>
    
      
  <li><%= link_to "Send a Moo", new_moo_path, class: "btn btn-primary btn-lg" %></li>
             <% else %>
     
     
  <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
     <% end %>
</div>